# Generated by Django 4.2.27 on 2026-01-30 12:37

from django.db import migrations, models
import utils.management.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuserpreferences',
            name='bin_user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=utils.management.file_rename.upload_to_user_profile_pic),
        ),
    ]
