# Generated by Django 4.2.27 on 2026-02-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_alter_mstaddrtypes_cod_addr_type_and_more'),
        ('user', '0002_alter_secuserpreferences_bin_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secusermaster',
            name='cod_time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='masters.msttimezone'),
        ),
    ]
