# Generated by Django 4.2.27 on 2026-02-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_sysemailtemplates'),
        ('campaign', '0038_cmpcallercredentials'),
        ('user', '0004_secusermaster_created_by_secusermaster_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secusermaster',
            name='cod_home_menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_home_menu', to='masters.secmenuoptions'),
        ),
        migrations.AlterField(
            model_name='secusermaster',
            name='id_parent_company_3rdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_master', to='campaign.mstthirdparties'),
        ),
    ]
