# Generated by Django 4.2.27 on 2026-02-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_secusermaster_cod_home_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secusermaster',
            name='txt_parent_company_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_parent_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
