# Generated by Django 4.2.27 on 2026-01-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_mstdepartments_id_third_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mststatecodes',
            unique_together={('cod_state', 'cod_rec_status')},
        ),
        migrations.RemoveField(
            model_name='mststatecodes',
            name='cod_country',
        ),
    ]
