# Generated by Django 4.2.27 on 2026-01-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_mststatecodes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mststatecodes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='cod_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states_list', to='masters.mstcountrycodes'),
        ),
        migrations.AlterUniqueTogether(
            name='mststatecodes',
            unique_together={('cod_state', 'cod_country', 'cod_rec_status')},
        ),
    ]
