# Generated by Django 4.2.27 on 2026-01-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_alter_cmpcampaignscripts_id_campaign_wave'),
        ('masters', '0008_alter_mststatecodes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstdepartmentsupportteam',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments_support_team', to='campaign.mstthirdparties'),
        ),
    ]
