# Generated by Django 4.2.27 on 2026-01-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_alter_cmpcampaignscripts_id_campaign_wave'),
        ('masters', '0009_alter_mstdepartmentsupportteam_id_third_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mstdepartmentsupportteam',
            unique_together={('cod_department', 'cod_rec_status', 'id_third_party')},
        ),
        migrations.RemoveField(
            model_name='mstdepartmentsupportteam',
            name='txt_login_id',
        ),
    ]
