# Generated by Django 4.2.27 on 2026-01-19 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0010_alter_mstdepartmentsupportteam_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_login_id',
            field=models.ForeignKey(blank=True, db_column='txt_login_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_team_memberships', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
    ]
