# Generated by Django 4.2.27 on 2026-01-21 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0011_mstdepartmentsupportteam_txt_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysCssTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_theme', models.CharField(max_length=4)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('txt_theme_name', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_theme_desc', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_css_file', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_default', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_css_themes',
                'unique_together': {('cod_theme', 'cod_rec_status')},
            },
        ),
    ]
