# Generated by Django 4.2.27 on 2026-01-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_syscsstheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstmajorcity',
            name='cod_city',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mstmajorcity',
            name='cod_city_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_city', to='masters.mstcityclasses'),
        ),
    ]
