# Generated by Django 4.2.27 on 2026-01-30 10:37

from django.db import migrations, models
import utils.management.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_alter_mstmajorcity_cod_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secmenuoptions',
            name='bin_menu_icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.management.file_rename.upload_to_menuoption),
        ),
    ]
