# Generated by Django 4.2.27 on 2026-02-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_alter_secmenuoptions_bin_menu_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstdepartments',
            name='cod_parent_department',
        ),
        migrations.RemoveField(
            model_name='mstdepartments',
            name='txt_dept_deputy_id',
        ),
        migrations.RemoveField(
            model_name='mstdepartments',
            name='txt_dept_head_id',
        ),
    ]
