# Generated by Django 4.2.27 on 2026-02-02 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0015_remove_mstdepartments_cod_parent_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstdepartments',
            name='cod_parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='masters.mstdepartments'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_dept_deputy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dept_deputy_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_dept_head_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dept_head_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
