# Generated by Django 4.2.27 on 2026-02-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_mstdepartments_cod_parent_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstmajorcity',
            name='cod_time_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_cities', to='masters.msttimezone'),
        ),
    ]
