# Generated by Django 4.2.27 on 2026-02-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_cmpcampaignxchannels'),
        ('masters', '0017_alter_mstmajorcity_cod_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstuserdesignation',
            name='id_third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.mstthirdparties'),
        ),
    ]
