# Generated by Django 4.2.27 on 2026-02-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_alter_mstuserdesignation_id_third_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secmenuoptions',
            name='cod_parent_menu_option',
        ),
    ]
