# Generated by Django 4.2.27 on 2026-02-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_remove_secmenuoptions_cod_parent_menu_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='secmenuoptions',
            name='cod_parent_menu_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_menus', to='masters.secmenuoptions'),
        ),
    ]
