# Generated by Django 4.2.27 on 2026-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_secmenuoptions_cod_parent_menu_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstaddrtypes',
            name='cod_addr_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='secmenuoptions',
            name='bin_menu_icon',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
