# Generated by Django 4.2.27 on 2026-02-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0023_remove_mstaddrtypes_txt_last_checker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaddrtypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstauditchecklist',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstaudittypes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcityclasses',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcountrycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcreditofficerlevels',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcurrency',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartments',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdepartmentsupportteam',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisabilitycodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosurelang',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdisclosures',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstdistrictcodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstlanguages',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstmajorcity',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstpincodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mststatecodes',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='msttimezone',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstuserdesignation',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='secmenuoptions',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='syscsstheme',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
    ]
