# Generated by Django 4.2.27 on 2026-02-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0037_cmpcampaigns_txt_last_checker_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0024_mstaddrtypes_txt_last_checker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysEmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_email_template', models.CharField(max_length=4)),
                ('txt_template_name', models.CharField(blank=True, max_length=96, null=True)),
                ('flg_public', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_request_read_receipt', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('flg_request_delivery_receipt', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('num_hours_1st_reminder', models.SmallIntegerField(default=72)),
                ('num_hours_2nd_reminder', models.SmallIntegerField(default=168)),
                ('txt_deeplink_url', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_deeplink_params', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Rejected'), ('C', 'Closed'), ('X', 'Cancelled')], max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_send_replies_to_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_from_template', to=settings.AUTH_USER_MODEL)),
                ('txt_sender_email_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_email_template', to=settings.AUTH_USER_MODEL)),
                ('txt_stored_proc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_template_proc', to='campaign.mstqareviewprocedure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'db_table': 'sys_email_templates',
                'unique_together': {('cod_email_template', 'cod_rec_status')},
            },
        ),
    ]
