# Generated by Django 4.2.27 on 2026-01-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_cmpcampaigns_bin_logo_to_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_camp_mgr_id',
        ),
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_invoice_sent_to_id',
        ),
    ]
