# Generated by Django 4.2.27 on 2026-01-06 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0007_remove_cmpcampaigns_txt_camp_mgr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_camp_mgr_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_invoice_sent_to_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmpcampaigns',
            name='id_commissioned_by_thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.mstthirdparties'),
        ),
    ]
