# Generated by Django 4.2.27 on 2026-01-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_cmpcampaigns_txt_camp_mgr_id_cmpwaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpcampaigns',
            name='id_commissioned_by_thirdparty',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.mstthirdparties'),
        ),
    ]
