# Generated by Django 4.2.27 on 2026-01-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_alter_cmpcampaigns_id_commissioned_by_thirdparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_qa_review_proc_name',
        ),
    ]
