# Generated by Django 4.2.27 on 2026-01-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_remove_cmpcampaigns_txt_qa_review_proc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstQAReviewProcedure',
            fields=[
                ('id_proc', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_proc_name', models.CharField(max_length=96, unique=True)),
            ],
            options={
                'db_table': 'mst_qa_review_procedures',
            },
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='id_qa_review_proc',
            field=models.ForeignKey(blank=True, db_column='id_qa_review_proc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviews', to='campaign.mstqareviewprocedure'),
        ),
    ]
