# Generated by Django 4.2.27 on 2026-01-08 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0008_alter_mststatecodes_unique_together_and_more'),
        ('campaign', '0012_mstqareviewprocedure_cmpcampaigns_id_qa_review_proc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_campaign_role', models.SmallIntegerField(blank=True, null=True)),
                ('txt_campaign_role', models.CharField(blank=True, max_length=48, null=True)),
                ('dat_joined_team', models.DateField(blank=True, null=True)),
                ('dat_left_team', models.DateField(blank=True, null=True)),
                ('flg_campaign_approval_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_questionnaire_approval_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_script_approval_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_flyer_approval_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_administrator', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_caller_role', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_allow_response_submit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_campaign_approval_rqstd', models.DateField(blank=True, null=True)),
                ('dat_questionnaire_approval_rqstd', models.DateField(blank=True, null=True)),
                ('dat_script_approval_rqstd', models.DateField(blank=True, null=True)),
                ('dat_flyer_approval_rqstd', models.DateField(blank=True, null=True)),
                ('dat_campaign_approved', models.DateField(blank=True, null=True)),
                ('dat_questionnaire_approved', models.DateField(blank=True, null=True)),
                ('dat_script_approved', models.DateField(blank=True, null=True)),
                ('dat_flyer_approved', models.DateField(blank=True, null=True)),
                ('num_contacts_capacity', models.SmallIntegerField(blank=True, null=True)),
                ('num_batch_size', models.SmallIntegerField(blank=True, null=True)),
                ('flg_escalation_notice', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_level_escalation', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], db_index=True, default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_preferred_lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam_team_lang', to='masters.mstlanguages')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='campaign.cmpcampaigns')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
                ('txt_login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_teams', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
            ],
            options={
                'db_table': 'cmp_team',
                'indexes': [models.Index(fields=['id_campaign'], name='cmp_team_id_camp_3630c2_idx'), models.Index(fields=['txt_login_id'], name='cmp_team_txt_log_dd7267_idx')],
                'unique_together': {('id_campaign', 'txt_login_id', 'cod_rec_status')},
            },
        ),
    ]
