# Generated by Django 4.2.27 on 2026-01-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0014_alter_cmpcampaigns_txt_invoice_sent_to_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPersonalizationTags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_tag', models.CharField(max_length=4)),
                ('txt_tag', models.CharField(max_length=48)),
                ('txt_tag_description', models.CharField(blank=True, max_length=96, null=True)),
                ('enu_tag_type', models.CharField(blank=True, choices=[('M', 'Message'), ('A', 'Alert'), ('U', 'Universal')], max_length=1, null=True)),
                ('num_display_sequence', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], db_index=True, default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_personalization_tags',
                'ordering': ['num_display_sequence', 'cod_tag'],
                'unique_together': {('cod_tag', 'cod_rec_status')},
            },
        ),
    ]
