# Generated by Django 4.2.27 on 2026-01-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_cmpcontactlistcolumns'),
        ('masters', '0008_alter_mststatecodes_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0015_syspersonalizationtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCampaignScripts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_intro_script', models.TextField(blank=True, null=True)),
                ('txt_ack_script', models.TextField(blank=True, null=True)),
                ('txt_not_qualified_script', models.TextField(blank=True, null=True)),
                ('txt_flyer_file', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], db_index=True, default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_scripts', to='contact.mstcontactchannel')),
                ('cod_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_scripts', to='masters.mstlanguages')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='campaign.cmpcampaigns')),
                ('id_campaign_wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='campaign.cmpwaves')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_campaign_scripts',
                'indexes': [models.Index(fields=['id_campaign'], name='cmp_campaig_id_camp_672963_idx'), models.Index(fields=['cod_channel'], name='cmp_campaig_cod_cha_22c557_idx'), models.Index(fields=['cod_language'], name='cmp_campaig_cod_lan_a06d0f_idx')],
                'unique_together': {('id_campaign', 'cod_channel', 'cod_language', 'cod_rec_status')},
            },
        ),
    ]
