# Generated by Django 4.2.27 on 2026-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_alter_cmpcampaigns_txt_invoice_sent_to_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpcampaignscripts',
            name='id_campaign_wave',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
