# Generated by Django 4.2.27 on 2026-01-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_alter_cmpcampaignscripts_id_campaign_wave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CmpWaves',
        ),
    ]
