# Generated by Django 4.2.27 on 2026-01-22 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_syscsstheme'),
        ('questionnaries', '0017_alter_cmpquestionoptions_id_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0007_cmpcontactlistfiles'),
        ('campaign', '0021_delete_cmpwaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpWaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_campaign_wave', models.BigIntegerField()),
                ('txt_campaign_wave_name', models.CharField(blank=True, max_length=96, null=True)),
                ('dat_wave_start', models.DateField(blank=True, null=True)),
                ('dat_wave_end', models.DateField(blank=True, null=True)),
                ('flg_one_question_format', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('num_tot_response_reqd', models.IntegerField(blank=True, null=True)),
                ('num_escalation_levels', models.SmallIntegerField(default=0)),
                ('num_hours_to_escalation', models.SmallIntegerField(default=48)),
                ('num_low_rating_below', models.SmallIntegerField(default=6)),
                ('num_high_rating_above', models.SmallIntegerField(default=9)),
                ('flg_test_wave', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_css_theme', models.ForeignKey(blank=True, db_column='cod_css_theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='masters.syscsstheme')),
                ('id_campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wave', to='campaign.cmpcampaigns')),
                ('id_contact_list', models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='contact.cmpcontactlist')),
                ('id_questionnaire', models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waves', to='questionnaries.cmpquestionnaire')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
                ('txt_wave_delivery_head_id', models.ForeignKey(blank=True, db_column='txt_wave_delivery_head_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_delivery_head', to=settings.AUTH_USER_MODEL)),
                ('txt_wave_requisitioner_id', models.ForeignKey(blank=True, db_column='txt_wave_requisitioner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_requisitioner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Wave',
                'verbose_name_plural': 'Campaign Waves',
                'db_table': 'cmp_waves',
                'unique_together': {('id_campaign', 'id_campaign_wave')},
            },
        ),
    ]
