# Generated by Django 4.2.27 on 2026-01-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0022_cmpwaves'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmpwaves',
            unique_together={('id_campaign',)},
        ),
        migrations.RemoveField(
            model_name='cmpwaves',
            name='id_campaign_wave',
        ),
    ]
