# Generated by Django 4.2.27 on 2026-01-27 09:13

from django.db import migrations, models
import utils.management.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0023_alter_cmpwaves_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstthirdparties',
            name='bin_third_party_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.management.file_rename.upload_to_third_Party),
        ),
    ]
