# Generated by Django 4.2.27 on 2026-01-27 13:11

from django.db import migrations, models
import utils.management.file_rename


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0024_alter_mstthirdparties_bin_third_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstthirdparties',
            name='bin_poa_doc',
            field=models.ImageField(blank=True, null=True, upload_to=utils.management.file_rename.upload_to_third_Party_poa),
        ),
    ]
