# Generated by Django 4.2.27 on 2026-01-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_alter_mstmajorcity_cod_city_and_more'),
        ('campaign', '0025_alter_mstthirdparties_bin_poa_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCampaignGeoCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_city_name', models.CharField(max_length=96)),
                ('num_responses_reqd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cod_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstcountrycodes')),
                ('cod_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstdistrictcodes')),
                ('cod_pin_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mstpincodes')),
                ('cod_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='masters.mststatecodes')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geo_coverage', to='campaign.cmpcampaigns')),
            ],
            options={
                'db_table': 'cmp_campaign_geo_coverage',
                'unique_together': {('id_campaign', 'cod_country', 'cod_state', 'cod_district', 'txt_city_name', 'cod_pin_code')},
            },
        ),
    ]
