# Generated by Django 4.2.27 on 2026-01-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaries', '0017_alter_cmpquestionoptions_id_question_and_more'),
        ('campaign', '0026_cmpcampaigngeocoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_segment_name', models.CharField(max_length=48)),
                ('num_segment_sequence', models.IntegerField(blank=True, null=True)),
                ('num_segment_response_reqd', models.SmallIntegerField(blank=True, null=True)),
                ('num_contact_list_col', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('id_campaign', models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_segments', to='campaign.cmpcampaigns')),
                ('id_qualifying_question', models.ForeignKey(blank=True, db_column='id_qualifying_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmp_segments', to='questionnaries.cmpquestion')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_segments',
                'unique_together': {('id_campaign', 'cod_rec_status', 'txt_segment_name')},
            },
        ),
    ]
