# Generated by Django 4.2.27 on 2026-01-29 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0017_alter_cmpquestionoptions_id_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0027_cmpsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpSegmentSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_population_size', models.SmallIntegerField(blank=True, null=True)),
                ('num_segment_response_reqd', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_option', models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='questionnaries.cmpquestionoptions')),
                ('id_campaign', models.ForeignKey(blank=True, db_column='id_campaign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='campaign.cmpcampaigns')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_size_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_size_maker', to=settings.AUTH_USER_MODEL)),
                ('txt_segment_name', models.ForeignKey(blank=True, db_column='txt_segment_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segment_sizes', to='campaign.cmpsegment')),
            ],
            options={
                'db_table': 'cmp_segments_sizes',
                'unique_together': {('id_campaign', 'txt_segment_name', 'cod_rec_status', 'cod_option')},
            },
        ),
    ]
