# Generated by Django 4.2.27 on 2026-01-30 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0007_cmpcontactlistfiles'),
        ('campaign', '0028_cmpsegmentsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCampaignXChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_start', models.DateField(blank=True, null=True)),
                ('dat_end', models.DateField(blank=True, null=True)),
                ('flg_outbound', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('num_channel_response_reqd', models.SmallIntegerField(blank=True, null=True)),
                ('amt_billing_rate_per_contact', models.FloatField(blank=True, null=True)),
                ('cod_channel_redirect_on_fail', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_channel_redirect_on_success', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_channel_redirect_no_response', models.CharField(blank=True, max_length=4, null=True)),
                ('num_hours_no_response_wait', models.SmallIntegerField(blank=True, null=True)),
                ('txt_email_id_for_send', models.EmailField(blank=True, max_length=254, null=True)),
                ('txt_email_signature', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_send_from_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_smtp_client', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_enable_ssl', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_smtp_port', models.SmallIntegerField(blank=True, null=True)),
                ('txt_send_replies_to_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('txt_bounced_email_redirect_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('txt_pop3_username', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_imap_username', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_x_channel', to='contact.mstcontactchannel')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_x_channel', to='campaign.cmpcampaigns')),
                ('txt_cmp_chnl_manager_id', models.ForeignKey(blank=True, db_column='txt_cmp_chnl_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_campaign_x_channels',
                'unique_together': {('id_campaign', 'cod_channel')},
            },
        ),
    ]
