# Generated by Django 4.2.27 on 2026-02-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0029_cmpcampaignxchannels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaignscripts',
            name='id_campaign_wave',
        ),
    ]
