# Generated by Django 4.2.27 on 2026-02-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0030_remove_cmpcampaignscripts_id_campaign_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='id_campaign_wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='campaign.cmpwaves'),
        ),
    ]
