# Generated by Django 4.2.27 on 2026-02-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0031_cmpcampaignscripts_id_campaign_wave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='cod_product',
        ),
    ]
