# Generated by Django 4.2.27 on 2026-02-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_mstproddisclosures_cod_product_and_more'),
        ('campaign', '0032_remove_cmpcampaigns_cod_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpcampaigns',
            name='cod_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign', to='product.mstprodcodes'),
        ),
    ]
