# Generated by Django 4.2.27 on 2026-02-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0033_cmpcampaigns_cod_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_invoice_sent_to_id',
        ),
    ]
