# Generated by Django 4.2.27 on 2026-02-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0034_remove_cmpcampaigns_txt_invoice_sent_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpcampaigns',
            name='txt_invoice_sent_to_id',
            field=models.ForeignKey(blank=True, db_column='txt_invoice_sent_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
