# Generated by Django 4.2.27 on 2026-02-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0035_cmpcampaigns_txt_invoice_sent_to_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpcampaigns',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpcampaignscripts',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpcampaignscripts',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpsegment',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpsegment',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpsegmentsize',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpsegmentsize',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpteam',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpteam',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpwaves',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpwaves',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstcampaignteamrole',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstcampaignteamrole',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstcampaigntypes',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstcampaigntypes',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstthirdparties',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstthirdparties',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstthirdpartytypes',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstthirdpartytypes',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='syspersonalizationtags',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='syspersonalizationtags',
            name='txt_last_maker_id',
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaigns',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpcampaignscripts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpsegmentsize',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpteam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpwaves',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaignteamrole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstcampaigntypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdparties',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstthirdpartytypes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syspersonalizationtags',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
