# Generated by Django 4.2.27 on 2026-02-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_mstcontactchannel_txt_last_checker_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0025_sysemailtemplates'),
        ('campaign', '0037_cmpcampaigns_txt_last_checker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpCallerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_certification_level', models.SmallIntegerField(default=1)),
                ('dat_first_certified', models.DateField(blank=True, null=True)),
                ('dat_certificate_valid_to', models.DateField(blank=True, null=True)),
                ('num_total_mthly_call_capacity', models.SmallIntegerField(blank=True, null=True)),
                ('num_mthly_valid_call_target', models.SmallIntegerField(blank=True, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials_channel', to='contact.mstcontactchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('txt_caller_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials_authorized', to=settings.AUTH_USER_MODEL)),
                ('txt_caller_base_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_base_city', to='masters.mstcityclasses')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, db_column='txt_last_checker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_last_maker_id', models.ForeignKey(blank=True, db_column='txt_last_maker_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id')),
                ('txt_login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cmp_caller_credentials', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caller Credential',
                'db_table': 'cmp_caller_credentials',
                'unique_together': {('txt_login_id', 'cod_rec_status')},
            },
        ),
    ]
