# Generated by Django 4.2.27 on 2026-02-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0038_cmpcallercredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpcampaigns',
            name='id_commissioned_by_thirdparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.mstthirdparties'),
        ),
    ]
