# Generated by Django 4.2.27 on 2026-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_mstcontracttypes_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpContactListColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact_list', models.BigIntegerField()),
                ('num_column', models.SmallIntegerField()),
                ('num_col_starts_at', models.SmallIntegerField(blank=True, null=True)),
                ('num_col_ends_at', models.SmallIntegerField(blank=True, null=True)),
                ('txt_col_header', models.CharField(blank=True, max_length=96, null=True)),
                ('enu_col_display_type', models.CharField(blank=True, choices=[('B', 'Boolean'), ('A', 'Alphanumeric'), ('N', 'Numeric'), ('D', 'Date')], max_length=1, null=True)),
                ('flg_segment_identifier', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_high_priority', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Contact List Column',
                'verbose_name_plural': 'Contact List Columns',
                'db_table': 'cmp_contact_list_columns',
                'unique_together': {('id_contact_list', 'num_column')},
            },
        ),
    ]
