# Generated by Django 4.2.27 on 2026-01-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_cmpcontactlistcolumns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmpcontactlistcolumns',
            unique_together={('num_column',)},
        ),
        migrations.RemoveField(
            model_name='cmpcontactlistcolumns',
            name='id_contact_list',
        ),
    ]
