# Generated by Django 4.2.27 on 2026-01-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0005_alter_cmpcontactlistcolumns_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpContactList',
            fields=[
                ('id_contact_list', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_contact_list_name', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_first_row_headers', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_import_from_row', models.SmallIntegerField(default=1)),
                ('flg_delimited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_tab_delimited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_pipe_delimited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_colon_delimited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_semicolon_delimited', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_other_delimters', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_consecutive_delimiters_as_one', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_qualifier_char', models.CharField(blank=True, max_length=4, null=True)),
                ('num_days_use_by', models.SmallIntegerField(default=0)),
                ('num_days_use_after', models.SmallIntegerField(default=0)),
                ('num_uniq_customer_id_col', models.SmallIntegerField(blank=True, null=True)),
                ('txt_360_view_url', models.CharField(blank=True, max_length=255, null=True)),
                ('num_customer_segment_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_recent_actvty_desc_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_recent_actvty_date_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_recent_actvty_location_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_recent_actvty_channel_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_recent_actvty_prod_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_offer_prod_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_offer_value_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_offer_valid_till_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_offer_price_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_offer_discount_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_first_name_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_last_name_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_salutation_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_primary_phone_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_alternative_phone_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_email_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_addr_line1_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_addr_line2_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_addr_line3_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_city_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_pincode_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_addr_country_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_rel_manager_name_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_rel_manager_email_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_rel_manager_phone_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_preferred_lang_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_emp_designation_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_emp_department_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_emp_reporting_mgr_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_rel_since_date_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_facebookid_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_twitterid_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_dnc_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_pref_time_to_call_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_addl_detail_url_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_bkgrd_img_url_col', models.SmallIntegerField(blank=True, null=True)),
                ('num_columns_in_file', models.SmallIntegerField(blank=True, null=True)),
                ('flg_saved_template', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_template_name', models.CharField(blank=True, max_length=96, null=True)),
                ('dat_time_list_created', models.DateTimeField(blank=True, null=True)),
                ('dat_time_list_reviewed', models.DateTimeField(blank=True, null=True)),
                ('txt_file_source', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_list_created_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('txt_list_owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('txt_list_reviewed_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Lists',
                'db_table': 'cmp_contact_list',
            },
        ),
    ]
