# Generated by Django 4.2.27 on 2026-01-22 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0006_cmpcontactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpContactListFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_upload_file_path', models.CharField(max_length=255)),
                ('txt_upload_file_name', models.CharField(max_length=255)),
                ('dat_time_file_upload_start', models.DateTimeField()),
                ('dat_time_file_upload_end', models.DateTimeField(blank=True, null=True)),
                ('num_rows_imported', models.IntegerField(blank=True, null=True)),
                ('num_list_item_start', models.IntegerField(blank=True, null=True)),
                ('num_list_item_end', models.IntegerField(blank=True, null=True)),
                ('txt_template_name', models.CharField(blank=True, max_length=96, null=True)),
                ('dat_time_list_reviewed', models.DateTimeField(blank=True, null=True)),
                ('txt_file_source', models.CharField(blank=True, max_length=48, null=True)),
                ('num_errors', models.SmallIntegerField(blank=True, null=True)),
                ('num_name_missing_error', models.SmallIntegerField(blank=True, null=True)),
                ('num_phone_missing_error', models.SmallIntegerField(blank=True, null=True)),
                ('num_email_missing_error', models.SmallIntegerField(blank=True, null=True)),
                ('num_address_missing_error', models.SmallIntegerField(blank=True, null=True)),
                ('num_typ_mismatch_error', models.SmallIntegerField(blank=True, null=True)),
                ('id_contact_list', models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='contact.cmpcontactlist')),
                ('txt_file_uploaded_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_list_file_uploader', to=settings.AUTH_USER_MODEL)),
                ('txt_list_reviewed_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_list_file_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact List File',
                'verbose_name_plural': 'Contact List Files',
                'db_table': 'cmp_contact_list_files',
                'unique_together': {('id_contact_list', 'txt_upload_file_path', 'txt_upload_file_name', 'dat_time_file_upload_start', 'txt_file_uploaded_by_id')},
            },
        ),
    ]
