# Generated by Django 4.2.27 on 2026-02-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_cmpcontactlistfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstcontactoutcome',
            name='cod_parent_outcome',
        ),
    ]
