# Generated by Django 4.2.27 on 2026-02-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_remove_mstcontactoutcome_cod_parent_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='cod_parent_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_contact_outcome', to='contact.mstcontactoutcome'),
        ),
    ]
