# Generated by Django 4.2.27 on 2026-02-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_mstcontactchannel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstcontactchannel',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstcontactchannel',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstcontactoutcome',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstcontactoutcome',
            name='txt_last_maker_id',
        ),
    ]
