# Generated by Django 4.2.27 on 2026-02-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0011_remove_mstcontactchannel_txt_last_checker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactchannel',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_checker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
        migrations.AddField(
            model_name='mstcontactoutcome',
            name='txt_last_maker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL, to_field='txt_login_id'),
        ),
    ]
