# Generated by Django 4.2.27 on 2026-02-13 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0038_cmpcallercredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0025_sysemailtemplates'),
        ('contact', '0012_mstcontactchannel_txt_last_checker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpContactsAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_list_item', models.BigIntegerField()),
                ('dat_time_assigned', models.DateTimeField()),
                ('dat_scheduled_contact', models.DateField(blank=True, null=True)),
                ('txt_pref_time_to_call', models.CharField(blank=True, max_length=48, null=True)),
                ('dat_do_not_call_after', models.DateField(blank=True, null=True)),
                ('flg_do_not_call', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('txt_last_responder_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_last_phone_contacted', models.CharField(blank=True, max_length=48, null=True)),
                ('id_response', models.BigIntegerField(default=0)),
                ('num_follow_up_level', models.SmallIntegerField(default=0)),
                ('dat_time_alert_email_sent', models.DateTimeField(blank=True, null=True)),
                ('txt_mime_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('num_hours_gmt_offset', models.FloatField(blank=True, null=True)),
                ('flg_deassigned', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('dat_time_deassigned', models.DateTimeField(blank=True, null=True)),
                ('txt_deassign_reason', models.CharField(blank=True, max_length=96, null=True)),
                ('cod_language', models.ForeignKey(blank=True, db_column='cod_language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.mstlanguages')),
                ('cod_pref_channel', models.ForeignKey(blank=True, db_column='cod_pref_channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_assignments', to='contact.mstcontactchannel')),
                ('id_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmp_contact_assigned', to='campaign.cmpcampaigns')),
                ('id_campaign_wave', models.ForeignKey(blank=True, db_column='cmp_contact_assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.cmpwaves')),
                ('id_contact_list', models.ForeignKey(blank=True, db_column='id_contact_list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmp_contact_assigned', to='contact.cmpcontactlist')),
                ('txt_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('txt_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned', to=settings.AUTH_USER_MODEL)),
                ('txt_deassigned_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deassigned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_contacts_assigned',
                'unique_together': {('id_campaign', 'id_campaign_wave', 'id_contact_list', 'num_list_item', 'txt_assigned_to', 'num_follow_up_level')},
            },
        ),
    ]
