# Generated by Django 4.2.27 on 2026-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstquestiontype',
            name='enu_display_type',
            field=models.CharField(blank=True, choices=[('A', 'Alpha'), ('B', 'Boolean'), ('C', 'Choice'), ('D', 'Date'), ('GL', 'Graph Large'), ('GM', 'Graph Medium'), ('GS', 'Graph Small'), ('GX', 'Graph Extra'), ('L', 'List'), ('M', 'Multi Select'), ('N', 'Numeric'), ('R', 'Rating'), ('RL', 'Rating List'), ('S', 'Single Select'), ('T', 'Text'), ('AV', 'Audio Visual'), ('CUSTOM', 'Custom')], max_length=10, null=True),
        ),
    ]
