# Generated by Django 4.2.27 on 2026-01-08 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaries', '0003_alter_mstquestiontype_enu_display_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestion',
            fields=[
                ('id_question', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt_question_text', models.TextField(blank=True, null=True)),
                ('txt_question_helptext', models.CharField(blank=True, default='', max_length=255)),
                ('txt_telecaller_prompt', models.CharField(blank=True, max_length=1024, null=True)),
                ('txt_addl_comments_prompt', models.CharField(blank=True, default='', max_length=255)),
                ('enu_display_type', models.CharField(choices=[('A', 'Alpha'), ('B', 'Boolean'), ('C', 'Choice'), ('D', 'Date'), ('GL', 'Graph Large'), ('GM', 'Graph Medium'), ('GS', 'Graph Small'), ('GX', 'Graph Extra'), ('L', 'List'), ('M', 'Multi Select'), ('N', 'Numeric'), ('R', 'Rating'), ('RL', 'Rating List'), ('S', 'Single Select'), ('T', 'Text'), ('AV', 'Audio Visual'), ('CUSTOM', 'Custom')], default='A', max_length=10)),
                ('num_rating_levels', models.SmallIntegerField(default=5)),
                ('flg_rating_base_zero', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_rating_one_highest', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_high_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_low_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('num_max_chars_response', models.SmallIntegerField(default=255)),
                ('txt_response_format', models.CharField(blank=True, max_length=255, null=True)),
                ('num_days_earliest', models.SmallIntegerField(default=-30000)),
                ('num_days_latest', models.SmallIntegerField(default=30000)),
                ('num_value_min', models.FloatField(default=-100000000000)),
                ('num_value_max', models.FloatField(default=100000000000)),
                ('flg_include_in_verbatim', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_question_bank', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], db_index=True, default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_question_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaries.mstquestionclass')),
                ('cod_question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questionnaries.mstquestiontype')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'cmp_questions',
            },
        ),
    ]
