# Generated by Django 4.2.27 on 2026-01-08 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0008_alter_mststatecodes_unique_together_and_more'),
        ('questionnaries', '0004_cmpquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_question_text', models.TextField(blank=True, null=True)),
                ('txt_question_helptext', models.CharField(blank=True, default='', max_length=255)),
                ('txt_telecaller_prompt', models.CharField(blank=True, max_length=1024, null=True)),
                ('txt_addl_comments_prompt', models.CharField(blank=True, default='', max_length=255)),
                ('txt_high_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_low_rating_label', models.CharField(blank=True, max_length=48, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('cod_language', models.ForeignKey(db_column='cod_language', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='masters.mstlanguages')),
                ('id_question', models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='questionnaries.cmpquestion')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Language',
                'verbose_name_plural': 'Question Languages',
                'db_table': 'cmp_questions_lang',
                'unique_together': {('id_question', 'cod_language', 'cod_rec_status')},
            },
        ),
    ]
