# Generated by Django 4.2.27 on 2026-01-09 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaries', '0006_alter_cmpquestion_id_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionnaire',
            fields=[
                ('id_questionnaire', models.BigIntegerField(primary_key=True, serialize=False)),
                ('txt_questionnaire_name', models.CharField(max_length=96)),
                ('txt_questionnaire_category', models.CharField(blank=True, max_length=48, null=True)),
                ('txt_target_audience', models.TextField(blank=True, null=True)),
                ('txt_research_objective', models.TextField(blank=True, null=True)),
                ('txt_created_by_id', models.CharField(blank=True, max_length=48, null=True)),
                ('dat_created_on', models.DateField(blank=True, null=True)),
                ('flg_public', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_print_format_file', models.CharField(blank=True, max_length=255, null=True)),
                ('flg_assessment', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_pass_score', models.SmallIntegerField(blank=True, null=True)),
                ('num_max_minutes_to_respond', models.SmallIntegerField(blank=True, null=True)),
                ('flg_randomize', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_show_score_on_submit', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_questionnaire',
                'indexes': [models.Index(fields=['id_questionnaire'], name='cmp_questio_id_ques_0f6735_idx'), models.Index(fields=['cod_rec_status'], name='cmp_questio_cod_rec_6c4b5d_idx')],
                'unique_together': {('id_questionnaire', 'cod_rec_status')},
            },
        ),
    ]
