# Generated by Django 4.2.27 on 2026-01-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0007_cmpquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpquestionnaire',
            name='id_questionnaire',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
