# Generated by Django 4.2.27 on 2026-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0008_alter_cmpquestionnaire_id_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpquestionnaire',
            name='id_questionnaire',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
