# Generated by Django 4.2.27 on 2026-01-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0009_alter_cmpquestionnaire_id_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionListTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_schema_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_table_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_code_col_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_descr_col_name', models.CharField(blank=True, max_length=96, null=True)),
                ('txt_where_clause', models.TextField(blank=True, null=True)),
                ('txt_order_by_clause', models.CharField(blank=True, max_length=255, null=True)),
                ('id_question', models.OneToOneField(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_table', to='questionnaries.cmpquestion')),
            ],
            options={
                'verbose_name': 'Question List Table',
                'verbose_name_plural': 'Question List Tables',
                'db_table': 'cmp_question_list_tables',
            },
        ),
    ]
