# Generated by Django 4.2.27 on 2026-01-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0010_cmpquestionlisttables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_keywords_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_question_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('id_question', models.OneToOneField(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='questionnaries.cmpquestion')),
            ],
            options={
                'verbose_name': 'Question Keyword',
                'verbose_name_plural': 'Question Keywords',
                'db_table': 'cmp_question_keywords',
            },
        ),
        migrations.CreateModel(
            name='CmpQuestionListValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_value', models.CharField(max_length=4)),
                ('num_seq', models.SmallIntegerField(blank=True, null=True)),
                ('txt_value', models.CharField(blank=True, max_length=255, null=True)),
                ('id_question', models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_values', to='questionnaries.cmpquestion')),
            ],
            options={
                'verbose_name': 'Question List Value',
                'verbose_name_plural': 'Question List Values',
                'db_table': 'cmp_question_list_values',
                'unique_together': {('id_question', 'cod_value')},
            },
        ),
    ]
