# Generated by Django 4.2.27 on 2026-01-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0011_cmpquestionkeywords_cmpquestionlistvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_option', models.CharField(max_length=4)),
                ('txt_option_text', models.CharField(blank=True, max_length=255, null=True)),
                ('num_display_sequence', models.SmallIntegerField(blank=True, null=True)),
                ('flg_capture_addl_text', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('txt_additional_text_prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_parent_question_option', models.ForeignKey(blank=True, db_column='cod_parent_question_option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_options', to='questionnaries.cmpquestionoptions')),
                ('id_parent_question', models.ForeignKey(blank=True, db_column='id_parent_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_question_options', to='questionnaries.cmpquestion')),
                ('id_question', models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaries.cmpquestion')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'cmp_question_options',
                'unique_together': {('id_question', 'cod_option')},
            },
        ),
    ]
