# Generated by Django 4.2.27 on 2026-01-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0012_cmpquestionoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionnaireQuestionLinks',
            fields=[
                ('id_linked_question', models.BigAutoField(primary_key=True, serialize=False)),
                ('enu_link_type', models.CharField(choices=[('SHOW', 'Show'), ('HIDE', 'Hide'), ('LABL', 'Label Change'), ('MISC', 'Misc')], default='SHOW', max_length=4)),
                ('cod_option', models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='questionnaries.cmpquestionoptions')),
                ('id_question', models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='questionnaries.cmpquestion')),
                ('id_questionnaire', models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='questionnaries.cmpquestionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Question Link',
                'verbose_name_plural': 'Questionnaire Question Links',
                'db_table': 'cmp_questionnaire_question_links',
                'unique_together': {('id_questionnaire', 'id_question', 'cod_option', 'id_linked_question', 'enu_link_type')},
            },
        ),
    ]
