# Generated by Django 4.2.27 on 2026-01-19 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaries', '0013_cmpquestionnairequestionlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionnaireQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_question_sequence', models.SmallIntegerField()),
                ('num_question_page', models.SmallIntegerField(blank=True, null=True)),
                ('num_question_group', models.SmallIntegerField(blank=True, null=True)),
                ('txt_question_num', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_mandatory', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_min_options_reqd', models.SmallIntegerField(blank=True, null=True)),
                ('num_max_options_allowed', models.SmallIntegerField(blank=True, null=True)),
                ('flg_qualifying_question', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_hide_question', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_qualify_if_yes', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('id_redirect_if_yes', models.BigIntegerField(blank=True, null=True)),
                ('id_redirect_if_no', models.BigIntegerField(blank=True, null=True)),
                ('num_rating_escalation_threshold', models.SmallIntegerField(default=6)),
                ('num_rating_addl_text_threshold', models.SmallIntegerField(default=6)),
                ('flg_bold', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_italic', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_underline', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_font_size', models.SmallIntegerField(blank=True, null=True)),
                ('txt_font_name', models.CharField(blank=True, max_length=48, null=True)),
                ('flg_include_in_report', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('enu_report_format', models.CharField(blank=True, choices=[('TBL', 'Table'), ('BAR', 'Bar'), ('PIE', 'Pie'), ('CLOUD', 'Cloud'), ('TIME', 'Time'), ('HEAT', 'Heat'), ('GEO', 'Geo')], max_length=5, null=True)),
                ('txt_keyword_substitutions', models.CharField(blank=True, max_length=255, null=True)),
                ('txt_theme', models.CharField(blank=True, max_length=96, null=True)),
                ('cod_rec_status', models.CharField(choices=[('A', 'Active'), ('N', 'New'), ('M', 'Modified'), ('R', 'Reviewed'), ('C', 'Cancelled'), ('X', 'Deleted')], default='A', max_length=1)),
                ('dat_last_maker', models.DateField(blank=True, null=True)),
                ('dat_last_checker', models.DateField(blank=True, null=True)),
                ('id_prerequisite_options', models.ManyToManyField(blank=True, related_name='questionnaire_prerequisites', to='questionnaries.cmpquestionoptions')),
                ('id_prerequisite_question', models.ForeignKey(blank=True, db_column='id_prerequisite_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='questionnaries.cmpquestion')),
                ('id_question', models.ForeignKey(db_column='id_question', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_mappings', to='questionnaries.cmpquestion')),
                ('id_questionnaire', models.ForeignKey(db_column='id_questionnaire', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='questionnaries.cmpquestionnaire')),
                ('txt_last_checker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checker', to=settings.AUTH_USER_MODEL)),
                ('txt_last_maker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cmp_questionnaire_questions',
                'unique_together': {('id_questionnaire', 'id_question', 'cod_rec_status')},
            },
        ),
    ]
