# Generated by Django 4.2.27 on 2026-01-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0014_cmpquestionnairequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpquestionnairequestions',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_mappings', to='questionnaries.cmpquestion'),
        ),
        migrations.AlterField(
            model_name='cmpquestionnairequestions',
            name='id_questionnaire',
            field=models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='questionnaries.cmpquestionnaire'),
        ),
    ]
