# Generated by Django 4.2.27 on 2026-01-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0015_alter_cmpquestionnairequestions_id_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpQuestionnaireQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_question_group', models.SmallIntegerField()),
                ('txt_group_header', models.TextField(blank=True, null=True)),
                ('num_min_response_reqd', models.SmallIntegerField(blank=True, null=True)),
                ('id_questionnaire', models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='questionnaries.cmpquestionnaire')),
            ],
            options={
                'db_table': 'cmp_questionnaire_question_group',
                'unique_together': {('id_questionnaire', 'num_question_group')},
            },
        ),
    ]
