# Generated by Django 4.2.27 on 2026-01-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaries', '0016_cmpquestionnairequestiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpquestionoptions',
            name='id_question',
            field=models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_options', to='questionnaries.cmpquestion'),
        ),
        migrations.CreateModel(
            name='CmpQuestionnaireQuestionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flg_escalation_reqd', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('flg_qualifying_response', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('num_answer_weight', models.FloatField(default=0)),
                ('flg_default', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('flg_exclude_option', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('id_option', models.ForeignKey(blank=True, db_column='cod_option', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_option_links', to='questionnaries.cmpquestionoptions')),
                ('id_question', models.ForeignKey(blank=True, db_column='id_question', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaries.cmpquestion')),
                ('id_questionnaire', models.ForeignKey(blank=True, db_column='id_questionnaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='questionnaries.cmpquestionnaire')),
                ('id_skip_to_question', models.ForeignKey(blank=True, db_column='id_skip_to_question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skip_from_options', to='questionnaries.cmpquestion')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'cmp_questionnaire_question_options',
                'unique_together': {('id_questionnaire', 'id_question', 'id_option')},
            },
        ),
    ]
