# Generated by Django 4.2.27 on 2026-02-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaries', '0017_alter_cmpquestionoptions_id_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpquestion',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestion',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionlang',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionlang',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionnaire',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionnaire',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionnairequestions',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='cmpquestionnairequestions',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstquestionclass',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstquestionclass',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstquestiontype',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstquestiontype',
            name='txt_last_maker_id',
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionlang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnaire',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cmpquestionnairequestions',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestionclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestiontype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstquestiontype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
