# Generated by Django 4.2.27 on 2026-02-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_mstpromocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstprodcodes',
            name='id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
