# Generated by Django 4.2.27 on 2026-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_populate_mstprodcodes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstprodcodes',
            name='cod_parent_product',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mstprodcodes',
            name='id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
