# Generated by Django 4.2.27 on 2026-02-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_map_parent_codes_to_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstprodcodes',
            name='cod_parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_product', to='product.mstprodcodes', to_field='id'),
        ),
    ]
