# Generated by Django 4.2.27 on 2026-02-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_mstprodcodes_cod_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstprodcodes',
            name='cod_parent_product',
        ),
        migrations.RemoveField(
            model_name='mstproddisclosures',
            name='cod_product',
        ),
        migrations.RemoveField(
            model_name='mstproddocs',
            name='cod_product',
        ),
        migrations.RemoveField(
            model_name='mstpromocodes',
            name='cod_product',
        ),
    ]
