# Generated by Django 4.2.27 on 2026-02-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_mstprodcodes_cod_parent_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MstProdCodes',
        ),
    ]
