# Generated by Django 4.2.27 on 2026-02-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_mstprodcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstproddisclosures',
            name='cod_product',
            field=models.ManyToManyField(blank=True, related_name='prod_disclosures', to='product.mstprodcodes'),
        ),
        migrations.AddField(
            model_name='mstproddocs',
            name='cod_product',
            field=models.ManyToManyField(blank=True, related_name='prod_docs', to='product.mstprodcodes'),
        ),
        migrations.AddField(
            model_name='mstpromocodes',
            name='cod_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.mstprodcodes'),
        ),
    ]
