# Generated by Django 4.2.27 on 2026-02-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_mstprodcodes_created_by_mstprodcodes_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstprodcodes',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstprodcodes',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstproddisclosures',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstproddisclosures',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstproddocs',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstproddocs',
            name='txt_last_maker_id',
        ),
        migrations.RemoveField(
            model_name='mstpromocodes',
            name='txt_last_checker_id',
        ),
        migrations.RemoveField(
            model_name='mstpromocodes',
            name='txt_last_maker_id',
        ),
        migrations.AddField(
            model_name='mstproddisclosures',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstproddisclosures',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstproddocs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstproddocs',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstpromocodes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mstpromocodes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
